import Vue from 'vue'
import { wrapFunctional } from './utils'

const components = {
  BannerDetails: () => import('../../components/BannerDetails.vue' /* webpackChunkName: "components/banner-details" */).then(c => wrapFunctional(c.default || c)),
  BannerHomeAid: () => import('../../components/BannerHomeAid.vue' /* webpackChunkName: "components/banner-home-aid" */).then(c => wrapFunctional(c.default || c)),
  BannerInfo: () => import('../../components/BannerInfo.vue' /* webpackChunkName: "components/banner-info" */).then(c => wrapFunctional(c.default || c)),
  Block1: () => import('../../components/Block1.vue' /* webpackChunkName: "components/block1" */).then(c => wrapFunctional(c.default || c)),
  Block2: () => import('../../components/Block2.vue' /* webpackChunkName: "components/block2" */).then(c => wrapFunctional(c.default || c)),
  Carousel: () => import('../../components/Carousel.vue' /* webpackChunkName: "components/carousel" */).then(c => wrapFunctional(c.default || c)),
  Company: () => import('../../components/Company.vue' /* webpackChunkName: "components/company" */).then(c => wrapFunctional(c.default || c)),
  CompanyQuote: () => import('../../components/CompanyQuote.vue' /* webpackChunkName: "components/company-quote" */).then(c => wrapFunctional(c.default || c)),
  CompanyQuoteCompanyDeal: () => import('../../components/CompanyQuoteCompanyDeal.vue' /* webpackChunkName: "components/company-quote-company-deal" */).then(c => wrapFunctional(c.default || c)),
  CompanyQuoteOwner: () => import('../../components/CompanyQuoteOwner.vue' /* webpackChunkName: "components/company-quote-owner" */).then(c => wrapFunctional(c.default || c)),
  Customer: () => import('../../components/Customer.vue' /* webpackChunkName: "components/customer" */).then(c => wrapFunctional(c.default || c)),
  Footer: () => import('../../components/Footer.vue' /* webpackChunkName: "components/footer" */).then(c => wrapFunctional(c.default || c)),
  FormProject: () => import('../../components/FormProject.vue' /* webpackChunkName: "components/form-project" */).then(c => wrapFunctional(c.default || c)),
  Header: () => import('../../components/Header.vue' /* webpackChunkName: "components/header" */).then(c => wrapFunctional(c.default || c)),
  HomeAidNav: () => import('../../components/HomeAidNav.vue' /* webpackChunkName: "components/home-aid-nav" */).then(c => wrapFunctional(c.default || c)),
  InputFile: () => import('../../components/InputFile.vue' /* webpackChunkName: "components/input-file" */).then(c => wrapFunctional(c.default || c)),
  Loading: () => import('../../components/Loading.vue' /* webpackChunkName: "components/loading" */).then(c => wrapFunctional(c.default || c)),
  Market: () => import('../../components/Market.vue' /* webpackChunkName: "components/market" */).then(c => wrapFunctional(c.default || c)),
  Modal: () => import('../../components/Modal.vue' /* webpackChunkName: "components/modal" */).then(c => wrapFunctional(c.default || c)),
  NewSiderbar: () => import('../../components/NewSiderbar.vue' /* webpackChunkName: "components/new-siderbar" */).then(c => wrapFunctional(c.default || c)),
  Pagination: () => import('../../components/Pagination.vue' /* webpackChunkName: "components/pagination" */).then(c => wrapFunctional(c.default || c)),
  ReceiveInfo: () => import('../../components/ReceiveInfo.vue' /* webpackChunkName: "components/receive-info" */).then(c => wrapFunctional(c.default || c)),
  DetailPayment: () => import('../../components/detailPayment.vue' /* webpackChunkName: "components/detail-payment" */).then(c => wrapFunctional(c.default || c)),
  DetailPaymentCompany: () => import('../../components/detailPaymentCompany.vue' /* webpackChunkName: "components/detail-payment-company" */).then(c => wrapFunctional(c.default || c)),
  PopupAddBankAccount: () => import('../../components/popup/addBankAccount.vue' /* webpackChunkName: "components/popup-add-bank-account" */).then(c => wrapFunctional(c.default || c)),
  PopupBankTransferSelect: () => import('../../components/popup/bankTransferSelect.vue' /* webpackChunkName: "components/popup-bank-transfer-select" */).then(c => wrapFunctional(c.default || c)),
  PopupDealUpdate: () => import('../../components/popup/dealUpdate.vue' /* webpackChunkName: "components/popup-deal-update" */).then(c => wrapFunctional(c.default || c)),
  PopupInforProject: () => import('../../components/popup/inforProject.vue' /* webpackChunkName: "components/popup-infor-project" */).then(c => wrapFunctional(c.default || c)),
  PopupLienhe: () => import('../../components/popup/lienhe.vue' /* webpackChunkName: "components/popup-lienhe" */).then(c => wrapFunctional(c.default || c)),
  PopupLienheform: () => import('../../components/popup/lienheform.vue' /* webpackChunkName: "components/popup-lienheform" */).then(c => wrapFunctional(c.default || c)),
  PopupPhoneform: () => import('../../components/popup/phoneform.vue' /* webpackChunkName: "components/popup-phoneform" */).then(c => wrapFunctional(c.default || c)),
  PopupSurvey: () => import('../../components/popup/survey.vue' /* webpackChunkName: "components/popup-survey" */).then(c => wrapFunctional(c.default || c)),
  PopupSurveyContact: () => import('../../components/popup/surveyContact.vue' /* webpackChunkName: "components/popup-survey-contact" */).then(c => wrapFunctional(c.default || c)),
  PopupSurveyCustomerContact: () => import('../../components/popup/surveyCustomerContact.vue' /* webpackChunkName: "components/popup-survey-customer-contact" */).then(c => wrapFunctional(c.default || c)),
  PopupSurveyUpdate: () => import('../../components/popup/surveyUpdate.vue' /* webpackChunkName: "components/popup-survey-update" */).then(c => wrapFunctional(c.default || c)),
  PopupViewSurvey: () => import('../../components/popup/viewSurvey.vue' /* webpackChunkName: "components/popup-view-survey" */).then(c => wrapFunctional(c.default || c)),
  PopupVilla: () => import('../../components/popup/villa.vue' /* webpackChunkName: "components/popup-villa" */).then(c => wrapFunctional(c.default || c)),
  ProfileAccount: () => import('../../components/profile/account.vue' /* webpackChunkName: "components/profile-account" */).then(c => wrapFunctional(c.default || c)),
  ProfileDes: () => import('../../components/profile/des.vue' /* webpackChunkName: "components/profile-des" */).then(c => wrapFunctional(c.default || c)),
  ProfileInfo: () => import('../../components/profile/info.vue' /* webpackChunkName: "components/profile-info" */).then(c => wrapFunctional(c.default || c)),
  ProfileManage: () => import('../../components/profile/manage.vue' /* webpackChunkName: "components/profile-manage" */).then(c => wrapFunctional(c.default || c)),
  ProfileManageCustomer: () => import('../../components/profile/manageCustomer.vue' /* webpackChunkName: "components/profile-manage-customer" */).then(c => wrapFunctional(c.default || c)),
  ProfileMenu: () => import('../../components/profile/menu.vue' /* webpackChunkName: "components/profile-menu" */).then(c => wrapFunctional(c.default || c)),
  ProfileProject: () => import('../../components/profile/project.vue' /* webpackChunkName: "components/profile-project" */).then(c => wrapFunctional(c.default || c)),
  ProfileRating: () => import('../../components/profile/rating.vue' /* webpackChunkName: "components/profile-rating" */).then(c => wrapFunctional(c.default || c)),
  QuoteForm: () => import('../../components/quote/form.vue' /* webpackChunkName: "components/quote-form" */).then(c => wrapFunctional(c.default || c)),
  PopupPaymentCreateReport: () => import('../../components/popup/payment/createReport.vue' /* webpackChunkName: "components/popup-payment-create-report" */).then(c => wrapFunctional(c.default || c)),
  PopupPaymentCreateRequired: () => import('../../components/popup/payment/createRequired.vue' /* webpackChunkName: "components/popup-payment-create-required" */).then(c => wrapFunctional(c.default || c)),
  PopupPaymentCustomerCreateReport: () => import('../../components/popup/paymentCustomer/createReport.vue' /* webpackChunkName: "components/popup-payment-customer-create-report" */).then(c => wrapFunctional(c.default || c)),
  PopupPaymentCustomerCreateRequired: () => import('../../components/popup/paymentCustomer/createRequired.vue' /* webpackChunkName: "components/popup-payment-customer-create-required" */).then(c => wrapFunctional(c.default || c)),
  ProfileContractorComplete: () => import('../../components/profile/contractor/complete.vue' /* webpackChunkName: "components/profile-contractor-complete" */).then(c => wrapFunctional(c.default || c)),
  ProfileContractorContent: () => import('../../components/profile/contractor/content.vue' /* webpackChunkName: "components/profile-contractor-content" */).then(c => wrapFunctional(c.default || c)),
  ProfileContractorDeploy: () => import('../../components/profile/contractor/deploy.vue' /* webpackChunkName: "components/profile-contractor-deploy" */).then(c => wrapFunctional(c.default || c)),
  ProfileContractorNegotiate: () => import('../../components/profile/contractor/negotiate.vue' /* webpackChunkName: "components/profile-contractor-negotiate" */).then(c => wrapFunctional(c.default || c)),
  ProfileContractorQuotes: () => import('../../components/profile/contractor/quotes.vue' /* webpackChunkName: "components/profile-contractor-quotes" */).then(c => wrapFunctional(c.default || c)),
  ProfileCustomerComplete: () => import('../../components/profile/customer/complete.vue' /* webpackChunkName: "components/profile-customer-complete" */).then(c => wrapFunctional(c.default || c)),
  ProfileCustomerContent: () => import('../../components/profile/customer/content.vue' /* webpackChunkName: "components/profile-customer-content" */).then(c => wrapFunctional(c.default || c)),
  ProfileCustomerDeploy: () => import('../../components/profile/customer/deploy.vue' /* webpackChunkName: "components/profile-customer-deploy" */).then(c => wrapFunctional(c.default || c)),
  ProfileCustomerNegotiate: () => import('../../components/profile/customer/negotiate.vue' /* webpackChunkName: "components/profile-customer-negotiate" */).then(c => wrapFunctional(c.default || c)),
  ProfileCustomerQuotes: () => import('../../components/profile/customer/quotes.vue' /* webpackChunkName: "components/profile-customer-quotes" */).then(c => wrapFunctional(c.default || c)),
  ProfileEditCompany: () => import('../../components/profile/edit/company.vue' /* webpackChunkName: "components/profile-edit-company" */).then(c => wrapFunctional(c.default || c)),
  ProfileEditConfirm: () => import('../../components/profile/edit/confirm.vue' /* webpackChunkName: "components/profile-edit-confirm" */).then(c => wrapFunctional(c.default || c)),
  ProfileEditPersonal: () => import('../../components/profile/edit/personal.vue' /* webpackChunkName: "components/profile-edit-personal" */).then(c => wrapFunctional(c.default || c)),
  ProfileEditProject: () => import('../../components/profile/edit/project.vue' /* webpackChunkName: "components/profile-edit-project" */).then(c => wrapFunctional(c.default || c)),
  ProfileEditWork: () => import('../../components/profile/edit/work.vue' /* webpackChunkName: "components/profile-edit-work" */).then(c => wrapFunctional(c.default || c)),
  ProfileFinanceBankAccount: () => import('../../components/profile/finance/bankAccount.vue' /* webpackChunkName: "components/profile-finance-bank-account" */).then(c => wrapFunctional(c.default || c)),
  ProfileFinanceBuy: () => import('../../components/profile/finance/buy.vue' /* webpackChunkName: "components/profile-finance-buy" */).then(c => wrapFunctional(c.default || c)),
  ProfileFinanceHistory: () => import('../../components/profile/finance/history.vue' /* webpackChunkName: "components/profile-finance-history" */).then(c => wrapFunctional(c.default || c)),
  ProfileFinanceManage: () => import('../../components/profile/finance/manage.vue' /* webpackChunkName: "components/profile-finance-manage" */).then(c => wrapFunctional(c.default || c)),
  ProfileFinanceRequest: () => import('../../components/profile/finance/request.vue' /* webpackChunkName: "components/profile-finance-request" */).then(c => wrapFunctional(c.default || c))
}

for (const name in components) {
  Vue.component(name, components[name])
  Vue.component('Lazy' + name, components[name])
}
