# serverless.yml
org: alexpham
app: econs
service: frontend
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ap-southeast-1
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  environment:
    # stops telemetry output from nuxt
    NUXT_TELEMETRY_DISABLED: 1

functions:
  nuxt:
    timeout: 30
    handler: app.handler
    events:
      - http: ANY /
      - http: ANY /{proxy+}

package:
  exclude:
    - pages
    - components
    - layout
    - pages

  include:
    # ensures that the build output gets packaged
    - .nuxt/**

plugins:
  - serverless-offline